resources:
  - name: sample_node
    type:   GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      branches:
        include: master

pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type:  Bash
        configuration:
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - echo "executing test Bash step step..."
            - add_pipeline_variables imageName="myimage" imageTag="master"
