resources:
  - name: sample_node
    type:   GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      branches:
        include: master

  - name: version
    type: FileSpec
    configuration:
      sourceArtifactory: ankul_artifactory
      pattern: promote-test/hello
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type:  Bash
        configuration:
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - printenv
            - echo "executing test Bash step..."
            
  - name: docker
    steps:
      - name: build_docker_image
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.66.107.45:8081/docker-virtual/ankul 
          dockerImageTag: $pipeline_name.$run_number
          inputResources:
            - name: sample_node
            - name: version
        execution:
          onComplete:
            - docker images       

  - name: ankul_pipeline_2
    configuration:
      environmentVariables:
        readOnly:
          ENV1: value1
          ENV2: value2
          ENV3: value3
      runtime:
        type: image
        image:
          custom:
            name: ankul/u16
            tag: master
          
    steps:
      - name: step_2
        type:  Bash
        configuration:
          inputResources:
            - name: sample_node
              trigger: false
        execution:
          onExecute:
            - printenv
            - echo "executing test Bash step..."
            - add_run_variables imageName="myimage1_$run_number" imageTag="master1_$run_number"
#             - touch $step_workspace_dir/upload/step_test.txt
#             - echo "someStepKey=somevalue" > $step_workspace_dir/upload/step_test.txt
#             - add_pipeline_variables imageName="myimage2_$run_number" imageTag="master2_$run_number"
#             - ls $pipeline_workspace_dir
#             - echo $pipelines_artifact_name

      - name: step_3
        type:  Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - printenv
            - echo "executing test Bash step..."
#             - add_pipeline_variables imageName="myimage3_$run_number" imageTag="master3_$run_number"
#             - ls $pipeline_workspace_dir
#             - echo $pipelines_artifact_name
