resources:
  - name: sample_node
    type: GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node

  - name: buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: go_publish_example
      buildNumber: 3
      
  - name: promoteinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: go_publish_example
      buildNumber: 3

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: Bash
        execution:
          onExecute:
            - echo "executing test bash step..."
            - printenv
            
      - name: promote
        type: PromoteBuild
        configuration:
          targetRepository: npm-test
          inputResources:
            - name: buildinfo
          outputResources:
            - name: promoteinfo
          inputSteps:
            - name: test_step

      - name: build_docker_image
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.66.110.173:8081/docker-local/ankul 
          dockerImageTag: $pipeline_name.$run_number
          inputResources:
            - name: sample_node
          inputSteps:
            - name: test_step

      - name: push_docker_image
        type: DockerPush
        configuration:
          targetRepository: ankul_local_repo
          autoPublishBuildInfo: true
          integrations:
            - name: ankul_artifactory
          inputSteps:
            - name: build_docker_image
