resources:
  - name: sample_node
    type:   GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      branches:
        include: master

pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type:  Bash
        configuration:
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - echo "executing test Bash step..."
            - add_pipeline_variables imageName="myimage_$run_number" imageTag="master_$run_number"
            - ls $pipeline_workspace_dir
            - echo $pipelines_artifact_name

      - name: step_2
        type:  Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "executing test Bash step..."
            - add_pipeline_variables imageName="myimage2_$run_number" imageTag="master2_$run_number"
            - ls $pipeline_workspace_dir
            - echo $pipelines_artifact_name
