resources:
  - name: files_in
    type: FileSpec
    configuration:
      sourceArtifactory: ankul_artifactory
      pattern: "npm-dev-local/"
      
  - name: files_out
    type: FileSpec
    configuration:
      sourceArtifactory: ankul_artifactory
      pattern: "npm-dev-local/"      

  - name: buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: test
      buildNumber: 11
      
  - name: promoteinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: test
      buildNumber: 11      

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: Bash
        execution:
          onExecute:
            - echo "executing test bash step..."
            - printenv
            
      - name: promote
        type: PromoteBuild
        configuration:
          tartgetRepository: npm-test
          inputResources:
            - name: files_in
          outputResources:
            - name: files_out
          inputSteps:
            - name: test_step
