resources:
  - name: buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: test
      buildNumber: 11

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: Bash
        execution:
          onExecute:
            - echo "executing test bash step..."
            - printenv
            
      - name: promote
        type: PromoteBuild
        configuration:
          inputSteps:
            - name: test_step
