resources:   
  - name: sample_node
    type: GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      branches:
        include: master
        
  - name: files
    type: FileSpec
    configuration:
      sourceArtifactory: ankul_artifactory
      pattern: docker-virtual/demo/
      limit: 2

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: Bash
        configuration:
#           nodePool: ankul_u16_nodes
          inputResources:
            - name: files
        execution:
          onExecute:
            - printenv

      - name: npm_build
        type: NpmBuild
        configuration:
#           nodePool: ankul_u16_nodes
          repositoryName: npm-dev-virtual
          sourceLocation: .
          integrations:
            - name: ankul_artifactory
          inputResources:
            - name: sample_node
            - name: files
          inputSteps:
            - name: test_step
           
      - name: npm_publish
        type: NpmPublish
        configuration:
#           nodePool: ankul_u16_nodes
          repositoryName: ankul-npm-publish
          integrations:
            - name: ankul_artifactory
          inputSteps:
            - name: npm_build
