resources:   
  - name: sample_node
    type: GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      branches:
        include: master
      tags:
        include: v1.0
        exclude: v1.1
      buildOn:
        commit: true
        pullRequestCreate: false
        pullRequestClose: false
        releaseCreate: false
        tagCreate: false
      shallowDepth: 10

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - echo "executing test bash step..."

      - name: npm_build
        type: NpmBuild
        configuration:
#           npmArgs: -g
          nodePool: ankul_u16_nodes
          repositoryName: npm-dev-virtual
          sourceLocation: .
          integrations:
            - name: ankul_artifactory
          inputResources:
            - name: sample_node
          inputSteps:
            - name: test_step
