syntaxVersion: v1.1
      
pipelines:
  - name: ankul_pipeline_4
    steps:
      - name: step_1
        type:  Bash
        configuration:
          nodePool: on-demand-nodes-c7
          runtime:
            type: image
            image:
              custom:
                name: ankul/u16
                tag: master
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - printenv
            - sleep 60
            - echo "executing test Bash step..."    
