# resources:      
#   - name: version
#     type: FileSpec
#     configuration:
#       sourceArtifactory: ankul_artifactory
#       pattern: ankul_local_repo/version.json
      
pipelines:
  - name: ankul_pipeline_3
    steps:
      - name: build_docker_image
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 34.66.110.173:8081/docker-local/ankul 
          dockerImageTag: $pipeline_name.$run_number
          inputResources:
            - name: sample_node
            - name: version
        execution:
          onComplete:
            - sudo apt-get install tree
            - tree $run_dir/workspace

      - name: push_docker_image
        type: DockerPush
        configuration:
          targetRepository: docker-local
          autoPublishBuildInfo: true
          integrations:
            - name: ankul_artifactory
#           inputSteps:
#             - name: build_docker_image
          outputResources:
            - name: buildinfo
        execution:
          onComplete:
            - sudo apt-get install tree
            - tree $run_dir/workspace
