resources:      
  - name: buildInfo
    type: buildInfo
    version:
      buildName: native_pipeline
      buildNumber: 8
      targetRepo: docker-local
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
          releaseBundleName: test_2
          releaseBundleVersion: v1.0.8
          dryRun: false
          description: "some random test description"
          releaseNotes:
            syntax: markdown
            content: "some random content release dasd asdas dasd aasdas"
        execution:
          onComplete:
            - printenv
        requires:
          integrations:
            - ankul_artifactory         
        triggeredBy:
          resources:
            - buildInfo
