resources:
  - name: sample_node
    type: GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      
pipelines:
  - name: ankul_pipeline_1
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: image_name
            tag: image_tag
            registry: ankul_artifactory
            sourceRepository: test_repo       
    steps:
      - name: p1_step_1
        type: Bash
        configuration:
          inputResources:
            - name: sample_node
        execution:
          onComplete:
            - echo true
            
            
  - name: ankul_pipeline_2
    steps:
      - name: p2_step_1
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: step_image_name
                tag: step_image_tag
                registry: ankul_github
                sourceRepository: step_test_repo
          inputResources:
            - name: sample_node
        execution:
          onComplete:
            - echo true
            
      - name: p2_step_2
        type: Bash
        configuration:
          inputResources:
            - name: sample_node
        execution:
          onComplete:
            - echo true            
