resources:
  - name: sample_node
    type:   GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      branches:
        include: master

pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - echo "executing test Bash step step_1..."
            
      - name: step_2
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "executing test Bash step step_2..."
            
      - name: step_3
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo "executing test Bash step step_3..." 
            
      - name: step_4
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_3
        execution:
          onExecute:
            - echo "executing test Bash step step_3..."             
