resources:
  - name: inReleaseBundle
    type: releaseBundle
    version:
      name: test_2
      version: v1.0.5
      
  - name: outReleaseBundle
    type: releaseBundle
    version:
      name: test_2
      version: v1.0.5         

pipelines:
  - name: ankul_pipelines_4
    steps:
      - name: signRelesae
        type: SignReleaseBundle
        configuration:
          nodePool: ankul_nodes      
        requires:
          integrations:
            - ankul_artifactory
          resources:
            - inReleaseBundle
        execute:
          onSuccess:
            - cat $STEP_TMP_DIR/curl_res_body
            - jq . $STEP_TMP_DIR/curl_res_body
        outputResources:
          - outReleaseBundle            
