resources:
  - name: files_in
    type: FileSpec
    configuration:
      sourceArtifactory: ankul_artifactory
      pattern: "npm-dev-local/"
      
  - name: files_out
    type: FileSpec
    configuration:
      sourceArtifactory: ankul_artifactory
      pattern: "npm-dev-local/"      

  - name: buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: go_publish_example
      buildNumber: 3
      
  - name: promoteinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: go_publish_example
      buildNumber: 3

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: Bash
        execution:
          onExecute:
            - echo "executing test bash step..."
            - printenv
            
      - name: promote
        type: PromoteBuild
        configuration:
          targetRepository: npm-test
          inputResources:
            - name: buildinfo
          outputResources:
            - name: promoteinfo
          inputSteps:
            - name: test_step
