resources:
  - name: sample_node
    type:   GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      branches:
        include: master
        
  - name: buildinfo_1
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11

  - name: buildinfo_2
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11
      
  - name: buildinfo_3
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11      

pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - echo "executing test Bash step step..."
            
      - name: step_2
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_1
          outputResources:
            - name: buildinfo_1
        execution:
          onExecute:
            - echo "executing test Bash step step..."
            
      - name: step_3
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "executing test Bash step step..." 
            
      - name: step_4
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "executing test Bash step step..."             

      - name: step_5
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_1
          inputSteps:
            - name: step_3
            - name: step_4
          outputResources:
            - name: buildinfo_2
        execution:
          onExecute:
            - echo "executing test Bash step step..."             

      - name: step_6
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_2
        execution:
          onExecute:
            - echo "executing test Bash step step..."    
            
      - name: step_7
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_6
        execution:
          onExecute:
            - echo "executing test Bash step step..." 
            
      - name: step_8
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_7
          outputResources:
            - name: buildinfo_3
        execution:
          onExecute:
            - echo "executing test Bash step step..."       
            
      - name: step_9
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_7
        execution:
          onExecute:
            - echo "executing test Bash step step..."  
            
      - name: step_10
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_3
          inputSteps:
            - name: step_9
        execution:
          onExecute:
            - echo "executing test Bash step step..."                          
            
      - name: step_11
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_10
        execution:
          onExecute:
            - echo "executing test Bash step step..."                                      
