resources:
  - name: sample_node
    type: GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      
pipelines:
  - name: ankul_pipeline_1  
    steps:
      - name: p1_step_1
        type: Bash
        configuration:
          nodePool: ankul_u16
          inputResources:
            - name: sample_node
          integrations:
            - name: ankul_github
        execution:
          onComplete:
            - echo true
 
      - name: p1_step_2
        type: Bash
        configuration:
          nodePool: ankul_u16
          runtime:
            type: image
            image:
              custom:
                name: ankul/u16all
                tag: master
                registry: ankul_docker
#                 sourceRepository: step_test_repo
          inputSteps:
            - name: p1_step_1
        execution:
          onExecute:
            - local userName=$(eval echo "$"int_"$dockerRegistry"_username)
            - local password=$(eval echo "$"int_"$dockerRegistry"_password)
            - local url=$(eval echo "$"int_"$dockerRegistry"_url)
            - retry_command docker login -u "$userName" -p "$password" "$url"
          onComplete:
            - echo true2
