resources:
  - name: files
    type: FileSpec
    configuration:
      sourceArtifactory: ankul_artifactory
    version:
      pattern: "npm-dev-local/"

  - name: buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: test
      buildNumber: 11
      
  - name: promoteinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: test
      buildNumber: 11      

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: Bash
        execution:
          onExecute:
            - echo "executing test bash step..."
            - printenv
            
      - name: promote
        type: PromoteBuild
        configuration:
          inputResources:
            - name: files
          inputSteps:
            - name: test_step
