resources:
#   - name: aql_invalid_yml
#     type: aql
#     version:
#       query: something
#       addedProperties:
#         ENV1: VALUE1
#         ENV2: VALUE2
#       mappings:
#         mapping0:
#           input: asda
#           output: asdsada

pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type: CreateReleaseBundle
