resources:      
  - name: buildInfo
    type: buildInfo
    version:
      buildName: native_pipeline
      buildNumber: 8
      targetRepo: docker-local
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
          releaseBundleName: test_2
          releaseBundleVersion: v1.0.8
          dryRun: false
          description: "some random test description"
          releaseNotes:
            syntax: markdown
            content: "\
"# Dillinger "\
"  - Type some Markdown on the left "\
"  - See HTML in the right "\
"  - Magic "\
"```sh "\
"$ cd dillinger "\
"$ npm install -d "\
"$ node app "\
"``` "\
        execution:
          onComplete:
            - printenv
        requires:
          integrations:
            - ankul_artifactory         
        triggeredBy:
          resources:
            - buildInfo
