resources:
  - name: sample_node
    type: GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      
pipelines:
  - name: ankul_pipeline_1  
    steps:
      - name: trigger_step
        type: Bash
        configuration:
          nodePool: ankul_u16
          inputResources:
            - name: sample_node
          integrations:
            - name: ankul_github
        execution:
          onComplete:
            - echo true

      - name: docker_pull
        type: Bash
        configuration:
          nodePool: ankul_u16
          runtime:
            type: image
            image:
              custom:
                name: ankul/u16all
                tag: master
                registry: ankul_docker
          inputSteps:
            - name: trigger_step
        execution:
          onExecute:
            - echo printenv
          onComplete:
            - echo true

      - name: aws_pull
        type: Bash
        configuration:
          nodePool: ankul_u16
          runtime:
            type: image
            image:
              custom:
                name: ankul/u16all
                tag: master
                registry: ankul_aws
                region: eu-west-2
          inputSteps:
            - name: trigger_step
        execution:
          onExecute:
            - echo printenv
          onComplete:
            - echo true
            
      - name: gcloud_pull
        type: Bash
        configuration:
          nodePool: ankul_u16
          runtime:
            type: image
            image:
              custom:
                name: ankul/u16all
                tag: master
                registry: ankul_gcloud
          inputSteps:
            - name: trigger_step
        execution:
          onExecute:
            - echo printenv
          onComplete:
            - echo true 
            
      - name: artifactory_pull
        type: Bash
        configuration:
          nodePool: ankul_u16
          runtime:
            type: image
            image:
              custom:
                name: ankul/u16all
                tag: master
                registry: art
                sourceRepository: test
          inputSteps:
            - name: trigger_step
        execution:
          onExecute:
            - echo printenv
          onComplete:
            - echo true             
