resources:      
  - name: buildInfo
    type: buildInfo
    version:
      buildName: native_pipeline
      buildNumber: 8
      targetRepo: docker-local
      
  - name: aql
    type: aql
    version:
      query: 'items.find({"$and":[{"artifact.module.build.name":{"$eq":"native_pipeline"}},{"artifact.module.build.number":{"$eq":"8"}}]})'     
      addedProperties:
        FOO: "value1a value1b"
        BAR: "value2a value2b"
      mappings:
        mapping0:
          input: "regex"
          output: "$1/$2"
        mapping2:
          input: "regex"
          output: "$2/$1"
  
  - name: releaseBundle
    type: releaseBundle
    version:
      name: test_2
      version: v1.1.3

pipelines:
  - name: ankul_pipeline
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
          releaseBundleName: test_2
          releaseBundleVersion: v1.1.3
          dryRun: false
          signed: false
          description: "some random test description"
          releaseNotes:
            syntax: markdown
            content: |
              ## Heading
                * Bullet
                * Points
        requires:
          integrations:
            - ankul_artifactory         
        triggeredBy:
          resources:
            - aql
        outputResources:
          - releaseBundle
        execution:
          onFailure:
            - jq -r ".resources.aql.resourceVersionContentPropertyBag" $STEP_JSON_PATH

      - name: signRelease
        type: SignReleaseBundle
        configuration:
          nodePool: ankul_nodes      
        requires:
          integrations:
            - ankul_artifactory
        triggeredBy:
          resources:
            - releaseBundle
        execution:
          onSuccess:
            - jq . $STEP_TMP_DIR/curl_res_body
