resources:
  - name: sample_node
    type: GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      
pipelines:
  - name: ankul_pipeline_1  
    steps:
      - name: p1_step_1
        type: Bash
        configuration:
          nodePool: ankul_u16
          inputResources:
            - name: sample_node
          integrations:
            - name: ankul_github
        execution:
          onComplete:
            - echo true
 
      - name: p1_step_2
        type: Bash
        configuration:
          nodePool: ankul_u16
          runtime:
            type: image
            image:
              custom:
                name: step_image_name
                tag: step_image_tag
                registry: ankul_artifactory
                sourceRepository: step_test_repo
          inputSteps:
            - name: p1_step_1
        execution:
          onComplete:
            - echo true2
