pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
          type: Bash
        configuration:
          integrations:
            - ankul_artifactory
        execution:
          onExecute:
            - echo "executing test bash step..."
