resources:      
  - name: buildInfo
    type: buildInfo
    version:
      buildName: test
      buildNumber: 17
      tartgetRepo: docker-local
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
          releaseBundleName: test_2
          releaseBundleVersion: v1.0.7
          dryRun: false
        requires:
          integrations:
            - ankul_artifactory         
        triggeredBy:
          resources:
            - buildInfo
