resources:
  - name: sample_node
    type:   GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      branches:
        include: master
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type:  Bash
        configuration:
          nodePool: custom-nodes
          runtime:
            type: image
            image:
              custom:
                name: ankul/u16
                tag: master          
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - printenv
            - sleep 60
            - echo "executing test Bash step..."    
            
  - name: ankul_pipeline_3
    steps:
      - name: step_1
        type:  Bash
        configuration:
          nodePool: on-demand-nodes-c7
          runtime:
            type: image
            image:
              custom:
                name: ankul/u16
                tag: master
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - sudo printenv
            - sudo echo 1
            - sudo echo 2
            - sudo echo 3 
            - sudo echo 1b
            - sudo echo 2b
            - sudo echo 3b             
            - sudo sleep 60
            - sudo echo "executing test Bash step..."  

  - name: ankul_pipeline_2
    configuration:
      environmentVariables:
        readOnly:
          ENV1: value1
          ENV2: value2
          ENV3: value3
      runtime:
        type: image
        image:
          custom:
            name: ankul/u16
            tag: master
          
    steps:
      - name: step_2
        type:  Bash
        configuration:
          nodePool: on-demand-nodes
          inputResources:
            - name: sample_node
              trigger: false
        execution:
          onExecute:
            - printenv
            - sleep 30
            - echo "executing test Bash step..."
            - add_run_variables imageName="myimage1_$run_number" imageTag="master1_$run_number"
#             - touch $step_workspace_dir/upload/step_test.txt
#             - echo "someStepKey=somevalue" > $step_workspace_dir/upload/step_test.txt
#             - add_pipeline_variables imageName="myimage2_$run_number" imageTag="master2_$run_number"
#             - ls $pipeline_workspace_dir
#             - echo $pipelines_artifact_name

      - name: step_3
        type:  Bash
        configuration:
          nodePool: on-demand-nodes
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - printenv
            - sleep 30
            - echo "executing test Bash step..."
#             - add_pipeline_variables imageName="myimage3_$run_number" imageTag="master3_$run_number"
#             - ls $pipeline_workspace_dir
#             - echo $pipelines_artifact_name
