resources:   
  - name: sample_node
    type: GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
#       files:
#         include: test.sh
#         exclude: random.sh
      branches:
        include: master
      tags:
        include: v1.0
        exclude: v1.1
      buildOn:
        commit: true
        pullRequestCreate: false
        pullRequestClose: false
        releaseCreate: false
        tagCreate: false
      shallowDepth: 10

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: bash
        configuration:
          nodePool: ankul_u16_nodes
        triggeredBy:
          resources:
            - sample_node
        execution:
          onExecute:
            - echo "executing test bash step..."

      - name: npm_build
        type: NpmBuild
        configuration:
          npmArgs: -g
          repositoryName: test_repo
          sourceLocation: .
        requires:
          integrations:
            - ankul_artifactory
          resources:
            - sample_node
          steps:
            - test_step
