resources:
  - name: aql
    type: aql
    version:
      query: items({})
      addedProperties:
        ENV1: VALUE1
        ENV2: VALUE2
      mappings:
        mapping0:
          input: test_input_0
          output: test_output_0
        mapping1:
          input: test_input_1
          output: test_output_1                             

pipelines:
  - name: ankul_pipeline
    steps:

      - name: test_bash_step
        type: bash
        requires:
          resources:
            - aql
        execution:
          onExecute:
            - printenv
            - cat $STEP_JSON_PATH
