resources:
  - name: mvn_repo
    type: GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_java
      
  - name: build_info_mvn
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: full-mvn-native
      buildNumber: 1
      
  - name: promoted_build_info_mvn
    type: BuildInfo
    configuration:
      sourceArtifactory: ankul_artifactory
      buildName: promotoed-full-mvn-native
      buildNumber: 1
      
  - name: unsigned_release_bundle_mvn
    type: ReleaseBundle
    configuration:
      sourceDistribution: ankul_artifactory
      name: unsigned_release_bundle_mvn
      version: v0.0.1
      isSigned: false
      
  - name: signed_release_bundle_mvn
    type: ReleaseBundle
    configuration:
      sourceDistribution: ankul_artifactory
      name: signed_release_bundle_mvn
      version: v1.0.0
      isSigned: true
      
  - name: distribution_rule_mvn
    type: DistributionRule
    configuration:
      sourceDistribution: ankul_artifactory
      cityName: "*"
      serviceName: "*"
      siteName: "*"
      countryCodes:
        - "GB"
        - "CN"
      
pipelines:
  - name: test_pipeline
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          sourceLocation: ./maven-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: mvn_repo
          integrations:
            - name: ankul_artifactory
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u16java
                tag: master
        execution:
          onStart:
            - javac -version
            - mvn --version


      - name: publish_build_info_mvn
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: build_info_mvn
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16java
                tag: master
                


      - name: promote_build_info_mvn
        type: PromoteBuild
        configuration:
          targetRepository: generic-local
          copy: true
          integrations:
            - name: ankul_artifactory 
          inputResources:
            - name: build_info_mvn
          outputResources:
            - name: promoted_build_info_mvn
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16java
                tag: master
                

      - name: release_mvn
        type: CreateReleaseBundle # needs admin access permission in JFrog Artifactory
        execution:
          onStart:
            - printenv
            - export integrationAlias=$(eval echo "$"res_"$buildInfo0"_integrationAlias)
            - echo $buildInfo0
            - echo $integrationAlias
            - eval echo "$"res_"$buildInfo0"_"$integrationAlias"_name
            - echo "$res_promoted_build_info_mvn_sourceArtifactory_name"
        configuration:
          dryRun: false
          description: "from github.com/scriptnull/jp - develop - full-mvn-native.yml"
          releaseBundleName: release_bundle_mvn
          releaseBundleVersion: v2.0.$run_number
          sign: false
          inputResources:
            - name: promoted_build_info_mvn
          outputResources:
            - name: unsigned_release_bundle_mvn
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16java
                tag: master
                

      - name: sign_mvn
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: unsigned_release_bundle_mvn
          outputResources:
            - name: signed_release_bundle_mvn
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16java
                tag: master   
                
      - name: distribute_signed_release_mvn
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_release_bundle_mvn
            - name: distribution_rule_mvn
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16java
                tag: master
