resources:
  - name: aql
    type: aql
    version:
      query: items({})
      addedProperties:
        ENV1: VALUE1
        ENV2: VALUE2
      mappings:
        mapping0:
          input: asda
          output: asdsada

pipelines:
  - name: ankul_pipeline
    steps:
      - name: bash
        type: bash
        execution:
          onExecute: 
            - echo something
            
      - name: bundle
        type: CreateReleaseBundle
        requires:
          steps:
            - bash
          integrations:
            - ankul_github
            - ankul_artifactory
