resources:
  - name: sample_node
    type:   GitRepo
    configuration:
      gitProvider: ankul_github
      path: ankul-shippable/sample_node
      branches:
        include: master
        
  - name: buildinfo_1
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11

  - name: buildinfo_2
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11
      
  - name: buildinfo_3
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11      
      
  - name: buildinfo_21
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11

  - name: buildinfo_22
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11
      
  - name: buildinfo_23
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11            

  - name: buildinfo_41
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11

  - name: buildinfo_42
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11
      
  - name: buildinfo_43
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 11

pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: sample_node
        execution:
          onExecute:
            - echo "executing test Bash step step..."
            
      - name: step_2
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_1
          outputResources:
            - name: buildinfo_1
        execution:
          onExecute:
            - echo "executing test Bash step step..."
            
      - name: step_3
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "executing test Bash step step..." 
            
      - name: step_4
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "executing test Bash step step..."             

      - name: step_5
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_1
          inputSteps:
            - name: step_3
            - name: step_4
          outputResources:
            - name: buildinfo_2
        execution:
          onExecute:
            - echo "executing test Bash step step..."             

      - name: step_6
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_2
        execution:
          onExecute:
            - echo "executing test Bash step step..."    
            
      - name: step_7
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_6
        execution:
          onExecute:
            - echo "executing test Bash step step..." 
            
      - name: step_8
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_7
          outputResources:
            - name: buildinfo_3
        execution:
          onExecute:
            - echo "executing test Bash step step..."       
            
      - name: step_9
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_7
        execution:
          onExecute:
            - echo "executing test Bash step step..."  
            
      - name: step_10
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_3
          inputSteps:
            - name: step_9
        execution:
          onExecute:
            - echo "executing test Bash step step..."                          
            
      - name: step_11
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_10
        execution:
          onExecute:
            - echo "executing test Bash step step..."                                   
            
      - name: step_21
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "executing test Bash step step..."                                         

      - name: step_22
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_21
          outputResources:
            - name: buildinfo_21
        execution:
          onExecute:
            - echo "executing test Bash step step..."
            
      - name: step_23
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_21
        execution:
          onExecute:
            - echo "executing test Bash step step..." 
            
      - name: step_24
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_21
        execution:
          onExecute:
            - echo "executing test Bash step step..."             

      - name: step_25
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_21
          inputSteps:
            - name: step_23
            - name: step_24
          outputResources:
            - name: buildinfo_22
        execution:
          onExecute:
            - echo "executing test Bash step step..."             

      - name: step_26
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_22
        execution:
          onExecute:
            - echo "executing test Bash step step..."    
            
      - name: step_27
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_26
        execution:
          onExecute:
            - echo "executing test Bash step step..." 
            
      - name: step_28
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_27
          outputResources:
            - name: buildinfo_23
        execution:
          onExecute:
            - echo "executing test Bash step step..."       
            
      - name: step_29
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_27
        execution:
          onExecute:
            - echo "executing test Bash step step..."  
            
      - name: step_30
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_23
          inputSteps:
            - name: step_29
        execution:
          onExecute:
            - echo "executing test Bash step step..."                          
            
      - name: step_31
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_30
        execution:
          onExecute:
            - echo "executing test Bash step step..." 

      - name: step_41
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "executing test Bash step step..."                                         

      - name: step_42
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_41
          outputResources:
            - name: buildinfo_41
        execution:
          onExecute:
            - echo "executing test Bash step step..."
            
      - name: step_43
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_41
        execution:
          onExecute:
            - echo "executing test Bash step step..." 
            
      - name: step_44
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_41
        execution:
          onExecute:
            - echo "executing test Bash step step..."             

      - name: step_45
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_41
          inputSteps:
            - name: step_43
            - name: step_44
          outputResources:
            - name: buildinfo_42
        execution:
          onExecute:
            - echo "executing test Bash step step..."             

      - name: step_46
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_42
        execution:
          onExecute:
            - echo "executing test Bash step step..."    
            
      - name: step_47
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_46
        execution:
          onExecute:
            - echo "executing test Bash step step..." 
            
      - name: step_48
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_47
          outputResources:
            - name: buildinfo_43
        execution:
          onExecute:
            - echo "executing test Bash step step..."       
            
      - name: step_49
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_47
        execution:
          onExecute:
            - echo "executing test Bash step step..."  
            
      - name: step_50
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputResources:
            - name: buildinfo_43
          inputSteps:
            - name: step_49
        execution:
          onExecute:
            - echo "executing test Bash step step..."                          
            
      - name: step_51
        type:  Bash
        configuration:
          nodePool: ankul_u16_nodes
          inputSteps:
            - name: step_50
        execution:
          onExecute:
            - echo "executing test Bash step step..." 
