resources:
  - name: inReleaseBundle
    type: releaseBundle
    version:
      name: test_2
      version: v1.0.1   
      
  - name: outReleaseBundle
    type: releaseBundle
    version:
      name: test_2
      version: v1.0.1         

pipelines:
  - name: ankul_pipelines_4
    steps:
      - name: signRelesae
        type: SignReleaseBundle
        configuration:
          nodePool: ankul_nodes      
        requires:
          integrations:
            - ankul_github
#           resources:
#             - releaseBundle
