resources:
  - name: inReleaseBundle
    type: releaseBundle
    version:
      name: test_2
      version: v1.0.4
      
  - name: outReleaseBundle
    type: releaseBundle
    version:
      name: test_2
      version: v1.0.4         

pipelines:
  - name: ankul_pipelines_4
    steps:
      - name: signRelesae
        type: SignReleaseBundle
        configuration:
          nodePool: ankul_nodes      
        requires:
          integrations:
            - ankul_artifactory
          resources:
            - inReleaseBundle          
        outputResources:
          - outReleaseBundle            
